// AUTO-GENERATED BY create-fullstack-feature
// DO NOT EDIT MANUALLY

export type DashboardNavItem = {
  labelKey: string;
  label: string;
  path: string;
};

export const generatedDashboardNav: DashboardNavItem[] = [
  {
    labelKey: "nav.category",
    label: "Category",
    path: "/dashboard/category",
  },
];
