// AUTO-GENERATED BY create-fullstack-feature
// DO NOT EDIT MANUALLY

import categoryReducer from "@/modules/category/slices/category.slice";

export const generatedReducers = {
  category: categoryReducer,
};
