// AUTO-GENERATED BY create-fullstack-feature
// DO NOT EDIT MANUALLY

import exampleReducer from "@/modules/example/slices/example.slice";

export const generatedReducers = {
  example: exampleReducer,
};
