// AUTO-GENERATED BY create-fullstack-feature
// DO NOT EDIT MANUALLY

using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace __PASCAL_NAME__.Infrastructure;

public static partial class DependencyInjection
{
    static partial void RegisterGeneratedInfrastructure(
        IServiceCollection services,
        IConfiguration configuration)
    {
        // Feature generator appends optional infrastructure registrations here.
    }
}
