// AUTO-GENERATED BY create-fullstack-feature
// DO NOT EDIT MANUALLY

import type { RouteObject } from "react-router-dom";
import ExamplesPage from "@/modules/example/pages/ExamplesPage";

export const generatedWebsiteRoutes: RouteObject[] = [
  { path: "/examples", element: <ExamplesPage /> },
];

export const generatedDashboardRoutes: RouteObject[] = [
  { path: "/dashboard/example", element: <ExamplesPage /> },
];
