// AUTO-GENERATED BY create-fullstack-feature
// DO NOT EDIT MANUALLY

import type { Routes } from "@angular/router";

export const generatedWebsiteRoutes: Routes = [
  {
    path: "categories",
    loadChildren: () =>
      import("../features/category/category.routes").then((m) => m.categoryRoutes),
  },
];

export const generatedDashboardRoutes: Routes = [
  {
    path: "category",
    loadChildren: () =>
      import("../features/category/category.routes").then((m) => m.categoryRoutes),
  },
];
