// AUTO-GENERATED BY create-fullstack-feature
// DO NOT EDIT MANUALLY

import type { Routes } from "@angular/router";

export const generatedWebsiteRoutes: Routes = [
  {
    path: "examples",
    loadChildren: () =>
      import("../features/example/example.routes").then((m) => m.exampleRoutes),
  },
];

export const generatedDashboardRoutes: Routes = [
  {
    path: "example",
    loadChildren: () =>
      import("../features/example/example.routes").then((m) => m.exampleRoutes),
  },
];
