// AUTO-GENERATED BY create-fullstack-feature
// DO NOT EDIT MANUALLY

import type { LucideIcon } from "lucide-react";
import { Boxes } from "lucide-react";

export type DashboardNavItem = {
  labelKey: string;
  label: string;
  href: string;
  icon: LucideIcon;
};

export const generatedDashboardNav: DashboardNavItem[] = [
  {
    labelKey: "nav.example",
    label: "Example",
    href: "/dashboard/example",
    icon: Boxes,
  },
];
